### PR TITLE
Bump sgx to 2.12 for docker & enable pdo-dev ubuntu 20.04

### PR DESCRIPTION
**Pull request by g2flyer**
As `apt update` bumps the sgx debian packages (not-so)auto-magically to latest version, i've tested PDO v2.12 and with a few caveat it still works.  As part of that i bumped the version also in the pdo-dev docker image and also enabled ubuntu 20.04.  I didn't update the docu, though, as it still does work with the old version and there is nothing short of ubuntu 20.04 support (which we currently do not support in PDO) according to the sgxsdk release notes ...

Now the caveats:
- `apt update` can result in a broken upgrade -- intel definitely doesn't have the strongest QA pipeline for these packages, every second upgrade breaks ... but a simple `apt --fix-broken install` does provide remedy
- it seems on FLC NUCs you now need the dcap driver (1.36.2), the old-style driver 2.11) does not seem to work anymore.  Note, though, that [download site](https://download.01.org/intel-sgx/sgx-linux/2.12/distro/ubuntu18.04-server/) provides both.
- as i was at it, i also tried to bump sgxssl from current `lin2.10_1.1.1.g` to latest `lin2.11_1.1.1.g`. Alas, that fails due to some not-really-documented changes they have done to pthreads in [this commit](https://github.com/intel/intel-sgx-ssl/commit/8c0866516ad6eb5f0bd47d15eced0d8c35723f2a) which makes `common/crypto` fail to build with 
```[ 90%] Linking CXX shared library ../../../libTestEnclave.so /opt/intel/sgxsdk.extras/external/toolset/ubuntu18.04/ld: /opt/intel/sgxssl/lib64/libsgx_tsgxssl_crypto.a(threads_pthread.o): in function `CRYPTO_THREAD_lock_new':
threads_pthread.c:(.text+0x45): undefined reference to `pthread_rwlock_init'```
  these functions were previously provided but now are removed. Not sure how exactly we pull them in. Didn't investigate much on how to resolve as i guess we do not have a need to upgrade and i have never looked at how we make use of pthreads; just a heads-up in case of anybody would have been tempted to try.
- lastly, the docker-image sets up properly with ubuntu 20.04, and even builds most of pdo until eventually fails with below. Didn't see a quick fix and i think there might be a few follow-up issues also on how we then test in docker-compose with sawtooth. So just a heads-up (e.g., if you need a sgx development environment based on 20.04, the dockerfile could be useful on its own).
```make[4]: Leaving directory '/project/pdo/src/private-data-objects/contracts/cdi/build'
make[3]: Leaving directory '/project/pdo/src/private-data-objects/contracts/cdi'
make[2]: Leaving directory '/project/pdo/src/private-data-objects/contracts'
 build.sh: operation failed: make all -j4
make[1]: *** [Makefile:121: build] Error 111
make[1]: Leaving directory '/project/pdo/src/private-data-objects/build'
make: Leaving directory '/project/pdo/src/private-data-objects/build'
make: *** [Makefile:124: verified-build] Error 2
Service 'pdo-build' failed to build: The command '/bin/sh -c echo "export PDO_SOURCE_ROOT=/project/pdo/src/private-data-objects" >> /etc/profile.d/pdo.sh  && . /etc/profile.d/pdo.sh  && echo "export SGX_MODE=${SGX_MODE}" >> /etc/profile.d/pdo.sh  && `/project/pdo/src/private-data-objects/build/common-config.sh -e`   && env | grep PDO | egrep -v 'PDO_ENCLAVE_CODE_SIGN_PEM|PDO_INSTALL_ROOT|PDO_HOME' | sed 's/^PDO/export PDO/g' >> /etc/profile.d/pdo.sh  && make -C /project/pdo/src/private-data-objects/build/ NO_SGX_RUN_DURING_BUILD=true  && echo '. /project/pdo/build/bin/activate' >> /etc/profile.d/pdo.sh  && . /project/pdo/build/bin/activate  && cd /project/pdo/src/private-data-objects  && sawtooth/bin/build_sawtooth_proto  && cd python  && python3 setup.py build_ext  && python3 setup.py install  && cd ../sawtooth  && python3 setup.py install  && cd /project/pdo/src/private-data-objects/eservice/  && sed -i 's/python /python3 /g' Makefile  && make  && make install  && python3 setup.py install  && cd ..  && sawtooth/bin/build_sawtooth_proto  && cd python/  && python3 setup.py install' returned a non-zero code: 2
Makefile:63: recipe for target 'pdo-composition' failed
make: *** [pdo-composition] Error 1
make: Leaving directory '/home/msteiner/src/projects/intel/PoET-et-al/pdo/src/PrivateDataObjects.git/docker'```

### CODE REVIEW

**Comment by g2flyer** [comment]
Uff, seems there are some (undocumented?) changes in pthread handling of sdk which also make wamr build fail:
```
...
runtime/core/shared/platform/linux-sgx/sgx_file.c:6:
/project/pdo/src/private-data-objects/interpreters/wasm-micro-runtime/core/shared/platform/linux-sgx/sgx_pthread.h:13:19: error: conflicting types for 'pthread_rwlock_t'
 typedef uintptr_t pthread_rwlock_t;
...
```
As it seems PDO (including WAMR) works on platform running 2.12 PSW but 2.10 SDK, i'm not debugging this but wait for some new version of WAMR and/or SDK ....

**Comment by bvavala** [comment]
closing for now -- #317 upgraded the sdk to 2.13, other upgrades will be done separately
